#!/usr/bin/env bash
set -e

# Please do not edit this file!

ENV=hiring-challenge-env

function log {
    local PURPLE='\033[0;35m'
    local NOCOLOR='\033[m'
    local BOLD='\033[1m'
    local NOBOLD='\033[0m'
    echo -e -n "${PURPLE}${BOLD}$1${NOBOLD}${NOCOLOR}" >&2
}

function install_miniconda {
    if ! [ -x "$(command -v conda)" ]; then
        log "Installing conda... "
        if [ "$(uname)" == "Darwin" ]; then local PLATFORM=MacOSX; else local PLATFORM=Linux; fi
        curl -k https://repo.anaconda.com/miniconda/Miniconda3-latest-"$PLATFORM"-x86_64.sh --output /tmp/miniconda.sh
        bash /tmp/miniconda.sh -b -f > /dev/null
        export PATH="$HOME/miniconda3/bin:$PATH"
        conda init > /dev/null
        log "Done!\\n"
    fi
    rm /tmp/miniconda.sh 2> /dev/null || true
}

function update_conda {
    log "Updating conda... "
    conda install mamba --channel conda-forge --yes > /dev/null
    mamba update --name base --yes conda > /dev/null
    log "Done!\\n"
}

function create_conda_env {
    log "Removing deprecated .envs directory... "
    local SCRIPT_PATH
    SCRIPT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
    rm -rf "$SCRIPT_PATH"/../.envs/
    conda config --remove envs_dirs .envs 2> /dev/null || true
    log "Done!\\n"

    log "Creating conda environment $ENV...\\n\\n"
    mamba env create --force
    log "Done!\\n"
}

# Initialise the environment
install_miniconda
update_conda
create_conda_env
